VIRTUAL_MECHANIC = {};

// Fuel min/max and 'levels' for main fuel gauge
VIRTUAL_MECHANIC.MIN_FUEL = 0;
VIRTUAL_MECHANIC.MAX_FUEL = 100;
VIRTUAL_MECHANIC.FUEL_GAUGE_LEVELS = 10;

// Fluid gauge min/max and caution/alert thresholds
VIRTUAL_MECHANIC.FLUID_GAUGE_MIN = 0;
VIRTUAL_MECHANIC.FLUID_GAUGE_MAX = 100;

VIRTUAL_MECHANIC.FLUID_WASHER_CAUTION = 20;
VIRTUAL_MECHANIC.FLUID_WASHER_ALERT = 10;
VIRTUAL_MECHANIC.FLUID_TRANSMISSION_CAUTION = 80;
VIRTUAL_MECHANIC.FLUID_TRANSMISSION_ALERT = 70;
VIRTUAL_MECHANIC.FLUID_FUEL_CAUTION = 25;
VIRTUAL_MECHANIC.FLUID_FUEL_ALERT = 10;
VIRTUAL_MECHANIC.FLUID_ENGINE_COOLANT_CAUTION = 80;
VIRTUAL_MECHANIC.FLUID_ENGINE_COOLANT_ALERT = 70;
VIRTUAL_MECHANIC.FLUID_BRAKE_CAUTION = 80;
VIRTUAL_MECHANIC.FLUID_BRAKE_ALERT = 70;

// Tire pressure/wear caution/alert thresholds
VIRTUAL_MECHANIC.SYSTEM_TIRE_PRESSURE_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_TIRE_PRESSURE_CAUTION_LOW = 27;
VIRTUAL_MECHANIC.SYSTEM_TIRE_PRESSURE_CAUTION_HIGH = 36;
VIRTUAL_MECHANIC.SYSTEM_TIRE_PRESSURE_ALERT_LOW = 24;
VIRTUAL_MECHANIC.SYSTEM_TIRE_PRESSURE_ALERT_HIGH = 38;

VIRTUAL_MECHANIC.SYSTEM_TIRE_WEAR_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_TIRE_WEAR_MAX = 100;
VIRTUAL_MECHANIC.SYSTEM_TIRE_WEAR_CAUTION = 30;
VIRTUAL_MECHANIC.SYSTEM_TIRE_WEAR_ALERT = 20;

// Brake wear status caution/alert thresholds
VIRTUAL_MECHANIC.SYSTEM_BRAKE_WEAR_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_BRAKE_WEAR_MAX = 100;
VIRTUAL_MECHANIC.SYSTEM_BRAKE_WEAR_CAUTION = 40;
VIRTUAL_MECHANIC.SYSTEM_BRAKE_WEAR_ALERT = 20;

// Engine status caution/alert thresholds and configuration
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_PRESSURE_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_PRESSURE_MAX = 100;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_PRESSURE_CAUTION_THRESHOLD = 85;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_PRESSURE_ALERT_THRESHOLD = 75;

VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_LEVEL_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_LEVEL_MAX = 100;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_LEVEL_CAUTION_THRESHOLD = 85;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_OIL_LEVEL_ALERT_THRESHOLD = 75;

VIRTUAL_MECHANIC.SYSTEM_ENGINE_RPM_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_RPM_CAUTION_THRESHOLD = 6250;
VIRTUAL_MECHANIC.SYSTEM_ENGINE_RPM_ALERT_THRESHOLD = 7000;

// Transmission status caution/alert thresholds and configuration
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_TEMPERATURE_MIN = -273.15;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_TEMPERATURE_MAX = 1000;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_TEMPERATURE_CAUTION = 215;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_TEMPERATURE_ALERT = 240;

VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_CLUTCH_WEAR_MIN = 0;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_CLUTCH_WEAR_MAX = 100;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_CLUTCH_WEAR_CAUTION = 60;
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_CLUTCH_WEAR_ALERT = 40;

VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_NEXT_SERVICE_DATE_FORMAT = 'mm/dd/yy';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_NEXT_SERVICE_CAUTION_THRESHOLD = 30;	// In days

VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_PARK = 'p';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_NEUTRAL = 'n';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_REVERSE = 'r';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_DRIVE = 'd';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_1 = '1';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_2 = '2';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_3 = '3';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_4 = '4';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_5 = '5';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_6 = '6';
VIRTUAL_MECHANIC.SYSTEM_TRANSMISSION_GEAR_7 = '7';

// Vehicle statistics configuration constants
VIRTUAL_MECHANIC.VEHICLE_STATS_MILEAGE_CONSUMPTION_UNIT = 'L';
VIRTUAL_MECHANIC.VEHICLE_STATS_MILEAGE_CONSUMPTION_PER = '100 km';
VIRTUAL_MECHANIC.VEHICLE_STATS_DISTANCE_UNIT = 'km';
VIRTUAL_MECHANIC.VEHICLE_STATS_AVG_SPEED_UNIT = 'km';

// added this to initialise config only after webworks is ready
VIRTUAL_MECHANIC.init = function () {
	// API Sensor constants
	VIRTUAL_MECHANIC.SENSOR_FUEL_LEVEL = car.sensors.Sensor.FUEL_LEVEL;
	VIRTUAL_MECHANIC.SENSOR_SPEED = car.sensors.Sensor.SPEED;

	VIRTUAL_MECHANIC.SENSOR_FLUID_WINDSHIELD_WASHER = car.sensors.Sensor.WASHERFLUID_LEVEL;
	VIRTUAL_MECHANIC.SENSOR_FLUID_TRANSMISSION = car.sensors.Sensor.TRANSMISSION_FLUID_LEVEL;
	VIRTUAL_MECHANIC.SENSOR_FLUID_ENGINE_COOLANT = car.sensors.Sensor.COOLANT_LEVEL;
	VIRTUAL_MECHANIC.SENSOR_FLUID_BRAKE = car.sensors.Sensor.BRAKE_FLUID_LEVEL;

	VIRTUAL_MECHANIC.SENSOR_TIRE_PRESSURE_RL = car.sensors.Sensor.TIRE_PRESSURE_REARLEFT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_PRESSURE_RR = car.sensors.Sensor.TIRE_PRESSURE_REARRIGHT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_PRESSURE_FL = car.sensors.Sensor.TIRE_PRESSURE_FRONTLEFT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_PRESSURE_FR = car.sensors.Sensor.TIRE_PRESSURE_FRONTRIGHT;

	VIRTUAL_MECHANIC.SENSOR_TIRE_WEAR_RL = car.sensors.Sensor.TIRE_WEAR_REARLEFT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_WEAR_RR = car.sensors.Sensor.TIRE_WEAR_REARRIGHT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_WEAR_FL = car.sensors.Sensor.TIRE_WEAR_FRONTLEFT;
	VIRTUAL_MECHANIC.SENSOR_TIRE_WEAR_FR = car.sensors.Sensor.TIRE_WEAR_FRONTRIGHT;

	VIRTUAL_MECHANIC.SENSOR_BRAKE_ABS_RL = car.sensors.Sensor.BRAKE_ABS_REARLEFT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_ABS_RR = car.sensors.Sensor.BRAKE_ABS_REARRIGHT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_ABS_FL = car.sensors.Sensor.BRAKE_ABS_FRONTLEFT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_ABS_FR = car.sensors.Sensor.BRAKE_ABS_FRONTRIGHT;

	VIRTUAL_MECHANIC.SENSOR_BRAKE_WEAR_RL = car.sensors.Sensor.BRAKE_PAD_WEAR_REARLEFT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_WEAR_RR = car.sensors.Sensor.BRAKE_PAD_WEAR_REARRIGHT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_WEAR_FL = car.sensors.Sensor.BRAKE_PAD_WEAR_FRONTLEFT;
	VIRTUAL_MECHANIC.SENSOR_BRAKE_WEAR_FR = car.sensors.Sensor.BRAKE_PAD_WEAR_FRONTRIGHT;

	VIRTUAL_MECHANIC.SENSOR_BRAKE_ABS = car.sensors.Sensor.BRAKE_ABS_ENABLED;

	VIRTUAL_MECHANIC.SENSOR_ENGINE_OIL_PRESSURE = car.sensors.Sensor.ENGINE_OIL_PRESSURE;
	VIRTUAL_MECHANIC.SENSOR_ENGINE_OIL_LEVEL = car.sensors.Sensor.ENGINE_OIL_LEVEL;
	VIRTUAL_MECHANIC.SENSOR_ENGINE_RPM = car.sensors.Sensor.RPM;

	VIRTUAL_MECHANIC.SENSOR_TRANSMISSION_TEMPERATURE = car.sensors.Sensor.TRANSMISSION_FLUID_TEMPERATURE;
	VIRTUAL_MECHANIC.SENSOR_TRANSMISSION_CURRENT_GEAR = car.sensors.Sensor.TRANSMISSION_GEAR;
	VIRTUAL_MECHANIC.SENSOR_TRANSMISSION_CLUTCH_WEAR = car.sensors.Sensor.TRANSMISSION_CLUTCH_WEAR;

	VIRTUAL_MECHANIC.SENSOR_LIGHT_TAIL_RL = car.sensors.Sensor.LIGHT_TAILLIGHT_LEFT;
	VIRTUAL_MECHANIC.SENSOR_LIGHT_TAIL_RR = car.sensors.Sensor.LIGHT_TAILLIGHT_RIGHT;
	VIRTUAL_MECHANIC.SENSOR_LIGHT_HEAD_FL = car.sensors.Sensor.LIGHT_HEADLIGHT_LEFT;
	VIRTUAL_MECHANIC.SENSOR_LIGHT_HEAD_FR = car.sensors.Sensor.LIGHT_HEADLIGHT_RIGHT;
}