#################################################
# This file is autogenerated from the deployment
# description, DO NOT EDIT
# (copied from VMware board)
#################################################
use_camera
    allow *

# Playbook
read_geolocation
    allow *
# BB10 phone 
access_location_services
    allow *

access_shared
    allow *
access_sys
    deny *
configure_system
    deny *
    allow qnx.navigator
    allow Shutdown*
    allow Settings*
record_audio
    # Can't prompt until dialog is implemented - PR 120238 
    #prompt *
    allow *

play_audio
    allow *
set_audio_volume
    allow *
post_notification
    allow *
access_bbid
    allow *
access_internet
    # Can't prompt until dialog is implemented - PR 120238 
    #prompt *
    allow *

use_installer
    deny *
    allow qnx.navigator

allow_app_purchase
    deny *
run_air_native
    allow *

_sys_use_consumer_push:signing_authority_controlled
    allow sys.apkruntime.gYABgKAOw1czN6neiAT72SGO.ns

apkruntime
    deny *
    allow sys.apkruntime.gYABgKAOw1czN6neiAT72SGO.ns

access_remote_frame_writer
    deny *
    allow sys.apkruntime.810

read_device_identifying_information
    allow *

manage_cert
    deny *
